### ISSUE TITLE
RL-AL with Reinvent4

### ISSUE THREAD

**Issue by djoy82** [MolecularAI/reinforcement-learning-active-learning#1]
HI all,

Thank you for this wonderful tool. I have recently moved on to REINVENT 4, and it allows me to easily used various custom models and scripts, among others. I am wondering if you are planning to update the tool to use REINVENT4. Thanks.

**Comment by djoy82** [comment]
Moreover, I have tried the code, but it seems it is missing the reinvent_models module, which was not mentioned in the setup docu. I was hoping to pull in the reinvent-models package from GitHub, but that one does not have molformer, which is required. Could you please advise as to what steps to take here?

**Comment by halx** [comment]
Hi,

many thanks for your interest in REINVENT and also welcome to the community!

I realize that this question is not direclty addressed to the REINVENT repository.  This repository here, I believe, has been published as part of a paper.

At the end of the day AL is a workflow solution where REINVENT is just one component.  We do not really have plans at the moment to provide a ready-made workflow for this other than what this repository provides.  We also have replaced the workflow software Icolos with maize.

The priors are located in the `priors/` directory in the REINVENT4 repository.

Many thanks,
Hannes.

**Comment by jpjanet** [comment]
Just to add to what Hannes mentioned, AL is separate layer that happens "on top" on ReInvent. The work in this repo was started during the end of R3 and so uses the old tools (R3 and Icolos), while we have moved to R4 and [Maize](https://arxiv.org/abs/2402.10064). AL functionality is/will be part of Maize going forward, see the example [Active learning](https://github.com/MolecularAI/maize-contrib/blob/e45b6002801d76c1b6c441a99dd78080ae281ef3/docs/reinvent-al.ipynb#L8). Questions about this should be directed to the Maize repo. 

We don't have plans to update this repo to R4 as such, but the AL workflow here is in Icolos, so it should/might work with the Icolos component in R4, since we still have the that legacy scoring component.

In response to your second comment, it looks like there is a version/import mismatch in this repo. @Detriatis  - would you be able to patch it? Mol2Mol (renamed from MolFormer) is not needed to run these experiments as they use the basic ReInvent only.

Best,
JP

**Comment by djoy82** [comment]
Hi all,

Sorry for the late reply. I have been on vacation. Thank you very much for your response. This is really helpful. I will take a closer look at Maize. Thank you for your contributions to this field.

Best.
Yannick
